name: bump version

on:
  pull_request:
    branches: ['main']
    types: [closed]
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Bump into new version
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  build:
    uses: ./.github/workflows/build.yml
  bump:
    needs: [build]
    uses: ./.github/workflows/shared-bump.yml
    permissions:
      contents: write
      id-token: write # Often needed for other tasks, good practice to include
    with:
      version: ${{ github.event.inputs.version }}
