# .github/workflows/[your_workflow].yml
name: bump version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        default: "patch"
        description: "major minor patch..."

jobs:
  
  bump:
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.X]

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.DEPLOY_KEY}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
      
      - name: Set version target
        id: defaultversion
        run: |
          TARGET=${{ github.event.inputs.version }}
          echo "version=${TARGET:-"patch"}" >> "$GITHUB_OUTPUT"
          
      - name: Version and Package
        run: npm version ${{steps.defaultname.outputs.version }}

      - name: Update git
        run: |
          git push --force
          git push --follow-tags --force
