# .github/workflows/[your_workflow].yml
name: bump version

on:
  pull_request:
    branches: ["main"]
    types: [opened]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  bump:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.X]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "bumps to version v{{version}}"
          tag-prefix: "v"
