# .github/workflows/[your_workflow].yml
name: bump version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        default: "patch"
        description: "major minor patch..."

jobs:
  build:
    uses: ./.github/workflows/build.yml
  bump:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.X]

    steps:     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.DEPLOY_KEY}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure git
        run: |         
          git config user.name "GitHubActions"
          git config user.email "${{secrets.OWNER}}"
      
      - name: Set default value
        id: defaultname
        run: |
          USER_INPUT=${{ github.event.inputs.version }}
          echo "value=${USER_INPUT:-"patch"}" >> "$GITHUB_OUTPUT"

      - name: Version and Package
        run: |
          name="${{ steps.defaultname.outputs.value }}"
          echo "Name: $name"
          npm version $name --force         

      - name: Update git
        run: |
          git push --force
          git push --follow-tags --force
